package ar.edu.unlam.dominio;

public enum OpcionesMenu {
	AGREGAR_VAGON, OBTENER_VAGON_DE_MENOR_PESO, OBTENER_PESO_PROMEDIO_DE_VAGONES_PARA_LA_MARCA, EDITAR_ID_DE_VAGON, ORDENAR_VAGONES_POR_ID_VAGON, SALIR
}
